# Generated by Django 2.2.6 on 2020-09-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='createTime',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
